version: "3.7"

services:
    db:
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - data:/var/lib/mysql
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: ${DB_PASSWORD}
    admin:
        image: adminer
        restart: always
        depends_on:
            - db
        ports:
            - 8080:8080

volumes:
    data:
