version: "3.7"

services:
    db:
        container_name: angelin.dev-db
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - data:/var/lib/mysql
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: ${DB_PASSWORD}
    admin:
        container_name: angelin.dev-adminer
        image: adminer
        restart: always
        depends_on:
            - db
        ports:
            - 8080:8080

networks:
    default:
        name: db
        external: true

volumes:
    data:
